---
# Install, configure and start PostgreSQL on remote server
- name: Install PostgreSQL server
  yum:
    name:
      - postgresql
      - postgresql-server
    state: present
  register: postgresql_installed

- name: Check if PostgreSQL is initialised
  stat: path=/var/lib/pgsql/data/postgresql.conf
  register: postgresql_conf

# ansible wants us to use the 'service' module for
# this but it doesn't work for 'initdb'
- name: Initialise PostgreSQL cluster
  command:
    service postgresql initdb
  when: postgresql_conf.stat.exists == False
  register: postgresql_initialised

- name: Update PostgreSQL authentication for postgres user
  lineinfile:
    dest=/var/lib/pgsql/data/pg_hba.conf
    line='local\tall\t    postgres\t\t\t      ident'
    insertafter='^# "local" is for Unix domain socket connections only'
    backup=yes
  notify:
    Restart PostgreSQL

- name: Update PostgreSQL authentication for all other users
  replace:
    dest=/var/lib/pgsql/data/pg_hba.conf
    regexp='^([^\s]+\s+all\s+all\s+.*)ident$'
    replace='\1md5'
  notify:
    Restart PostgreSQL

- name: Start PostgreSQL service and enable on boot
  service:
    name=postgresql
    state=started
    enabled=yes
  when: postgresql_initialised is success
  register: postgresql_started

