---
# Install, configure and start PostgreSQL on remote server

- name: "Report PostgreSQL version"
  debug:
    msg: "PostgreSQL version: '{{ postgresql_version }}'"

- name: "Install PostgreSQL signing key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8

- name: "Get PostgreSQL repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes

- name: "Install PostgreSQL server"
  apt:
    pkg:
      - "postgresql-client-{{ postgresql_version }}"
      - "postgresql-{{ postgresql_version }}"
      - "libpq-dev"
      - "postgresql-server-dev-{{ postgresql_version }}"
      - "postgresql-contrib"
    state: present

- name: "Set up PostgreSQL user authentication (pg_hba.conf)"
  copy:
    src: 'pg_hba.conf'
    dest: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'

- name: "Start PostgreSQL service"
  systemd:
    name: "postgresql"
    state: "restarted"
    enabled: yes
