---
- name: "Install Nginx for SL/CentOS"
  yum:
    name:
      - "{{ nginx_yum_package }}"
      - "libselinux-python"
      - "libsemanage-python"
      - "python-passlib"
    state: present

- name: "Get status of SELinux"
  command: getenforce
  register: sestatus
  changed_when: false

- name: "Set sebooleans for httpd"
  seboolean:
    name={{ item }} state=yes persistent=yes
  with_items:
    - httpd_can_network_connect
    - httpd_enable_homedirs
    - httpd_use_nfs
  when: "'Disabled' not in sestatus.stdout"
