---
# Install, configure and start Nginx on remote server
- name: "Install Nginx"
  yum:
    name:
      - "{{ nginx_yum_package }}"
      - "libselinux-python"
      - "libsemanage-python"
      - "python-passlib"
    state: present

- name: "Get status of SELinux"
  command: getenforce
  register: sestatus
  changed_when: false

- name: "Set sebooleans for httpd"
  seboolean:
    name={{ item }} state=yes persistent=yes
  with_items:
  - httpd_can_network_connect
  - httpd_enable_homedirs
  - httpd_use_nfs
  when: "'Disabled' not in sestatus.stdout"

- name: "Check if default Nginx configuration is present"
  stat: path={{ nginx_conf_dir }}/conf.d/default.conf
  register: nginx_default_conf

- name: "Move default Nginx configuration"
  command: "mv {{ nginx_conf_dir }}/conf.d/default.conf {{ nginx_conf_dir }}/conf.d/default.conf.bak"
  when: nginx_default_conf.stat.exists

# On Scientific Linux 7 the default nginx.conf file contains
# a 'server' block which clashes with the one in the Galaxy
# conf file, so need to replace it
- name: "Replace main Nginx conf file"
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    mode: "u=rw,go=r"
  when: ansible_distribution_major_version == "7"
  notify:
  - "Restart Nginx"

- name: "Start Nginx"
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: on
