---
# Install, configure and start Nginx on remote server
- name: "Install Nginx"
  apt:
    pkg:
      - "nginx"
    state: present

- name: "Check if default Nginx configuration is present"
  stat: path={{ nginx_conf_dir }}/conf.d/default.conf
  register: nginx_default_conf

- name: "Move default Nginx configuration"
  command: "mv {{ nginx_conf_dir }}/conf.d/default.conf {{ nginx_conf_dir }}/conf.d/default.conf.bak"
  when: nginx_default_conf.stat.exists

- name: "Start Nginx"
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: on
