---
- name: "Install build dependencies"
  yum:
    name:
      - 'git'
      - 'autoconf'
      - 'make'
      - 'automake'
      - 'gcc'
      - 'readline'
      - 'sqlite'
      - 'zlib'
      - 'bzip2-devel'
      - 'bzip2'
      - 'ncurses-devel'
      - 'ncurses'
      - 'openssl-devel'
      - 'openssl'
      - 'readline-devel'
      - 'sqlite-devel'
      - 'zlib-devel'
      - 'tkinter'
      - 'python-setuptools'
      - 'libffi'
      - 'libffi-devel'
      - 'xz'
      - 'xz-devel'
    state: 'present'
