---

- name: "Build tgz archive for export"
  shell:
    cmd: tar czf {{ galaxy_root_dir }}/shared/{{ archive_name }}.tgz -C {{ galaxy_root_dir }}/shared csf/galaxy/{{ galaxy_version }}/{{ galaxy_venv }} csf/python/{{ python_version }}

- name: "Export tgz from remote"
  fetch:
    src: "{{ galaxy_root_dir }}/shared/{{ archive_name }}.tgz"
    dest: "{{ assets_dir }}"
    flat: yes
