# Install Galaxy
---

- name: "Include tasks for installing system dependencies"
  include_tasks: dependencies.yml

- name: "Include tasks for setting up system user for Galaxy"
  include_tasks: galaxy_user.yml

- name: "Include tasks for building Python for Galaxy"
  include_tasks:
    file: python.yml
    apply:
      become: yes
      become_user: "{{ galaxy_user }}"

- name: "Include tasks for building Galaxy client virtualenv"
  include_tasks:
    file: galaxy.yml
    apply:
      become: yes
      become_user: "{{ galaxy_user }}"

- name: "Include tasks for exporting Galaxy client virtualenv"
  include_tasks:
    file: export.yml
    apply:
      become: yes
      become_user: "{{ galaxy_user }}"
  
