---
# Name for Galaxy instance
galaxy_name: "palfinder"
galaxy_version: 'release_20.09'

# User running Galaxy service
galaxy_user: "galaxy"
galaxy_group: "{{ galaxy_user }}"

# Galaxy admin user
galaxy_admin_user: "admin@galaxy.org"

# Postgresql database
galaxy_db: "galaxy_{{ galaxy_name }}"
galaxy_db_user: "{{ galaxy_user }}"
galaxy_db_password: "{{ galaxy_db_user }}"

# Web server
galaxy_server_name: "galaxy.example.org"
galaxy_id_secret:
galaxy_http_port: 8080

# Proxy prefix
# Leave blank for no prefix, otherwise must start
# with a forward slash e.g. "/galaxy"
galaxy_proxy_prefix:

# Welcome page template and static content
galaxy_welcome_template: "welcome.html.j2"
galaxy_terms:
galaxy_citations:

# (S)CSS styles/custom colours
# Define entries as a dictionary with:
# - var   (SCSS variable e.g. 'brand-primary')
# - value (Value e.g. 'red', '#660099')
galaxy_custom_scss: null

# Message of the day
# This message will be displayed under the masthead
# on the Galaxy site
galaxy_message:

# HTTPS parameters
enable_https: no
enable_certificate_renewal: yes
ssl_certificate: "/etc/ssl/certs/{{ galaxy_server_name }}"
ssl_certificate_key: "/etc/ssl/certs/{{ galaxy_server_name }}"

# Additional location entries in nginx config
# Define entries as a dictionary with:
# - location
# - alias
# - add_header (optional)
galaxy_nginx_extra_locations:

# Additional static content
# Define entries as a dictionary with:
# - src (file to be uploaded)
# - dest (target location)
# - link (option, also make a link to dest)
galaxy_extra_static_content:

# Galaxy source code
galaxy_repo: https://github.com/galaxyproject/galaxy.git

# Galaxy installation directories
galaxy_install_dir: "/home/galaxy/galaxies"
galaxy_dir: "{{ galaxy_install_dir }}/{{ galaxy_name }}"
galaxy_clone_dir: "galaxy"
galaxy_root: "{{ galaxy_dir }}/{{ galaxy_clone_dir }}"
galaxy_tool_dependency_dir: '{{ galaxy_dir }}/tool_dependencies'
galaxy_database_dir: '{{ galaxy_root }}/database'

# Files and working directories
galaxy_job_working_dir: "{{ galaxy_database_dir }}/jobs_directory"
galaxy_file_path: "{{ galaxy_database_dir }}/files"
galaxy_new_file_path: "{{ galaxy_database_dir }}/tmp"

# Database SQL file
# Set to a pg_dump SQL file from a previous Galaxy DB
# to reload data from that DB
# NB only used when creating a new DB (will not overwrite
# an existing database)
galaxy_new_db_sql:

# Tool data locations
galaxy_tool_data_path: "{{ galaxy_root }}/tool-data"
galaxy_shed_tool_data_path: "{{ galaxy_tool_data_path }}"
galaxy_data_manager_data_path: "{{ galaxy_tool_data_path }}"

# Python for Galaxy
galaxy_python_version: "3.6.11"
galaxy_python_dir: '{{ galaxy_dir }}/python/{{ galaxy_python_version }}'

# Toolshed check
enable_tool_shed_check: no

# Conda options
galaxy_conda_auto_install: yes

# Dependency caching options
galaxy_use_cached_depedency_manager: no

# User account creation and activation
allow_user_creation: yes
allow_user_deletion: yes
enable_user_activation: no

# User login
enable_require_login: no

# Quotas
enable_quotas: no

# Tool conf XML file
galaxy_tool_conf_file:

# How to handle clean up of artefacts left on the
# filesystem after job completion
# Should be 'always', 'onsuccess', or 'never'
galaxy_cleanup_job: "always"

# Allow admins to paste filesystem paths during upload
galaxy_allow_path_paste: no

# Tool data tables
# Define table entries as a dictionary with:
# - description (free text, inserted into comment)
# - name        (table name)
# - columns     (table columns as comma-separated values)
# - file_path   (path to .loc file relative to galaxy_root)
galaxy_tool_data_tables:

# Chromosome length files (.len)
# Should be a list of file names e.g. 'hg38.len'
galaxy_chromosome_len_files:

# Job runners
enable_drmaa: no
enable_jse_drop: no
galaxy_default_runner: "local"

# JSE-drop defaults
galaxy_jse_drop_galaxy_id: "{{ galaxy_name }}"
galaxy_jse_drop_dir: "{{ galaxy_dir }}/jse-drop"
galaxy_jse_drop_virtual_env: "{{ galaxy_root }}/.venv"
# Grace period after which files from deleted jobs
# can be removed (seconds)
galaxy_jse_drop_cleanup_grace_period: "600"

# Job destinations
# Define entries as a dictionary with:
# - id     (destination ID)
# - runner (target runner)
# - jse_drop_qsub_options (optional, JSE-drop 'qsub_options')
# - jse_drop_slots (optional, JSE-drop 'galaxy_slots')
# - envs (optional dictionary defining <env...> elements)
# 'envs' should be a dictionary with:
# - id     (ID for env element)
# - value  (corresponding env value)
galaxy_job_destinations:

# Tool destinations
# Define entries as a dictionary with:
# - id          (tool ID/name)
# - destination (target destination)
galaxy_tool_destinations:

# Dependency resolvers
# Define entries as a dictionary with:
# - type        (required; one of 'tool_shed_packages', 'galaxy_packages',
#                'conda')
# - versionless (optional; sets 'versionless' attribute to 'true' or 'false')
# - base_path   (optional; sets 'base_path' attribute)
galaxy_dependency_resolvers:
  - type: 'tool_shed_packages'
  - type: 'galaxy_packages'
  - type: 'galaxy_packages'
    versionless: 'true'
  - type: 'conda'
  - type: 'conda'
    versionless: 'true'

# Limits for number of concurrent running jobs
galaxy_registered_user_concurrent_jobs: 2
galaxy_unregistered_user_concurrent_jobs: 0
galaxy_concurrent_jobs: 2

# HTML sanitization whitelist
galaxy_sanitize_whitelist_file: "config/sanitize_whitelist.txt"
# List of paths for whitelisted tools e.g.
# galaxy_sanitize_whitelist_tools:
# - "toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.72"
# - ...
galaxy_sanitize_whitelist_tools:

# nginx configuration
nginx_client_body_temp_path: "/tmp/nginx"
nginx_client_max_body_size: "10G"
nginx_service: "nginx"
nginx_user: "nginx"
nginx_group: "nginx"
nginx_conf_dir: "/etc/nginx"
nginx_share_dir: "/usr/share/nginx"

# uWSGI configuration
galaxy_uwsgi_processes: 8
galaxy_uwsgi_socket: 4001
galaxy_reports_uwsgi_socket: 9001

# Galaxy handler processes
galaxy_handler_processes: 1

# Logging
galaxy_log_dir: "{{ galaxy_dir }}/logs"
enable_log_rotation: yes

# FTP uploads
enable_ftp_upload: no
galaxy_ftp_upload_dir: "{{ galaxy_dir }}/ftp_uploads"
galaxy_ftp_upload_site: "ftp://{{ galaxy_server_name }}"
galaxy_ftp_user: "{{ galaxy_user }}_ftp"
galaxy_ftp_password: "{{ galaxy_ftp_user }}"

# Outgoing mail notification settings
enable_smtp: no
galaxy_outgoing_email_addr: "Galaxy {{ galaxy_name }} <galaxy-no-reply@{{ galaxy_server_name  }}>"
galaxy_incoming_email_addr: "None"

# Reporting interface
enable_reports: no
galaxy_reports_htpasswd: "/etc/nginx/galaxy-reports.htpasswd"
galaxy_reports_user: "galaxyreports"
galaxy_reports_password: "{{ galaxy_reports_user }}"

# Location to install galaxy utilities
# Utilities should be installed under the 'bin' subdirectory
# of this location
galaxy_utils_dir: "/usr/local"

# GDPR Compliance mode
enable_beta_gdpr: no
