---
# Name for Galaxy instance
galaxy_name: "palfinder"
galaxy_version: 'release_17.09'

# User running Galaxy service
galaxy_user: "galaxy"
galaxy_group: "{{ galaxy_user }}"

# Galaxy admin user
galaxy_admin_user: "admin@galaxy.org"

# Python for Galaxy
galaxy_python_dir: '/usr/local'

# Postgresql database
galaxy_db: "galaxy_{{ galaxy_name }}"
galaxy_db_user: "{{ galaxy_user }}"
galaxy_db_password: "{{ galaxy_db_user }}"

# Web server
galaxy_server_name: "galaxy.example.org"
galaxy_id_secret:

# Proxy prefix
# Leave blank for no prefix, otherwise must start
# with a forward slash e.g. "/galaxy"
galaxy_proxy_prefix:

# Welcome page template and static content
galaxy_welcome_template: "welcome.html.j2"
galaxy_terms:
galaxy_citations:

# Message of the day
# This message will be displayed under the masthead
# on the Galaxy site
galaxy_message:

# HTTPS parameters
enable_https: no
ssl_certificate: "/etc/ssl/certs/{{ galaxy_server_name }}"
ssl_certificate_key: "/etc/ssl/certs/{{ galaxy_server_name }}"

# Additional location entries in nginx config
# Define entries as a dictionary with:
# - location
# - alias
# - add_header (optional)
galaxy_nginx_extra_locations:

# Additional static content
# Define entries as a dictionary with:
# - src (file to be uploaded)
# - dest (target location)
# - link (option, also make a link to dest)
galaxy_extra_static_content:

# Galaxy source code
galaxy_repo: https://github.com/galaxyproject/galaxy.git

# Galaxy installation directories
galaxy_install_dir: "/home/galaxy/galaxies"
galaxy_dir: "{{ galaxy_install_dir }}/{{ galaxy_name }}"
galaxy_root: "{{ galaxy_dir }}/galaxy"
galaxy_tool_dependency_dir: '{{ galaxy_dir }}/tool_dependencies'
galaxy_database_dir: '{{ galaxy_root }}/database'

# Files and working directories
galaxy_job_working_dir: "{{ galaxy_database_dir }}/jobs_directory"
galaxy_file_path: "{{ galaxy_database_dir }}/files"
galaxy_new_file_path: "{{ galaxy_database_dir }}/tmp"

# Tool data locations
galaxy_tool_data_path: "{{ galaxy_root }}/tool-data"
galaxy_shed_tool_data_path: "{{ galaxy_tool_data_path }}"
galaxy_data_manager_data_path: "{{ galaxy_tool_data_path }}"

# Conda options
galaxy_conda_auto_install: yes

# User account creation and activation
enable_allow_user_creation: yes
enable_user_activation: no

# User login
enable_require_login: no

# Quotas
enable_quotas: no

# Tool conf XML file
galaxy_tool_conf_file:

# How to handle clean up of artefacts left on the
# filesystem after job completion
# Should be 'always', 'onsuccess', or 'never'
galaxy_cleanup_job: "always"

# Allow admins to paste filesystem paths during upload
galaxy_allow_path_paste: no

# Job runners
enable_drmaa: no
enable_jse_drop: no
galaxy_default_runner: "local"

# JSE-drop defaults
galaxy_jse_drop_galaxy_id: "{{ galaxy_name }}"
galaxy_jse_drop_dir: "{{ galaxy_dir }}/jse-drop"
galaxy_jse_drop_virtual_env: "{{ galaxy_root }}/.venv"

# Job destinations
galaxy_job_destinations:

# Tool destinations
galaxy_tool_destinations:

# HTML sanitization whitelist
galaxy_sanitize_whitelist_file: "config/sanitize_whitelist.txt"
galaxy_sanitize_whitelist_tools:

# uWSGI configuration
galaxy_uwsgi_processes: 8

# Galaxy handler processes
galaxy_handler_processes: 1

# Logging
galaxy_log_dir: "{{ galaxy_dir }}/logs"

# FTP uploads
enable_ftp_upload: no
galaxy_ftp_upload_dir: "{{ galaxy_dir }}/ftp_uploads"
galaxy_ftp_upload_site: "ftp://{{ galaxy_server_name }}"
galaxy_ftp_user: "{{ galaxy_user }}_ftp"
galaxy_ftp_password: "{{ galaxy_ftp_user }}"

# Outgoing mail notification settings
enable_smtp: no
galaxy_outgoing_email_addr: "Galaxy {{ galaxy_name }} <galaxy-no-reply@{{ galaxy_server_name  }}>"
galaxy_incoming_email_addr: "None"

# Reporting interface
enable_reports: no
galaxy_reports_htpasswd: "/etc/nginx/galaxy-reports.htpasswd"
galaxy_reports_user: "galaxyreports"
galaxy_reports_password: "{{ galaxy_reports_user }}"
