---
# Install EPEL repository
- name: Check if EPEL repo is enabled
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_status

- name: Install EPEL repo 
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  when: epel_status.stat.exists == false

# Update 'nss' to make sure that EPEL repo can be accessed
#
# See:
# - https://github.com/GovReady/govready/issues/64
# - https://unix.stackexchange.com/a/163368/14641
- name: Update nss
  yum:
    name: nss
    state: latest
    disablerepo: "epel"
