centaurus:
  hosts:
    130.88.97.245
  vars:
    # Server name
    galaxy_server_name: "centaurus.itservices.manchester.ac.uk"
    # Galaxy configuation
    centaurus_galaxy_config: production.yml
    # Secrets
    centaurus_secrets: production_secrets.yml
    # Shed tools
    centaurus_shed_tools: shed_tools_minimal.yml
    # Tool data
    centaurus_tool_data: tool_data_full.yml
    # Welcome page template
    galaxy_welcome_template: "instances/centaurus/templates/centaurus-welcome.html.j2"
    # uWSGI and handler configuration
    galaxy_uwsgi_processes: 4
    galaxy_handler_processes: 4
    # JSE-Drop service
    enable_local_jse_drop: no
    # Job cleanup
    galaxy_cleanup_job: "onsuccess"
    # Postfix/email configuration
    enable_smtp: yes
    # Audit report
    email_audit_report_to: "{{ galaxy_admin_user }}"
    # SSL configuration
    enable_https: yes
    # Default quota
    default_quota_gb: 100