---
# Create the 'galaxy' user and group with specified UID/GIDs
- name: Create Galaxy group
  group:
    name={{ galaxy_group }} gid={{ galaxy_gid }} state=present

- name: Create Galaxy user
  user:
    name={{ galaxy_user }}
    group={{ galaxy_group }}
    home=/home/{{ galaxy_user }}
    uid={{ galaxy_uid }}
    shell="/bin/bash"
    state=present

- name: "Create additional groups"
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ extra_groups }}"
  when: extra_groups|default(None) != None

- name: "Add Galaxy user to additional groups"
  user:
    name: "{{ galaxy_user }}"
    groups: "{{ item.group }}"
    append: yes
  with_items: "{{ extra_groups }}"
  when: extra_groups|default(None) != None
