---
- hosts: centaurus

  vars:
  # Galaxy configuration
  - galaxy_name: "centaurus"
  - galaxy_version: "release_20.09"
  - galaxy_install_dir: "/mnt/rvmi/centaurus/galaxy"
  - galaxy_dir: "{{ galaxy_install_dir }}/production"
  - galaxy_clone_dir: "galaxy-dist"
  # Database and reference data
  - galaxy_file_path: "/mnt/bmh01-rvmi/bcf-galaxy/centaurus/production/database/files"
  - galaxy_job_working_dir: "/mnt/bmh01-rvmi/bcf-galaxy/centaurus/production/job_working_directory"
  - galaxy_data_manager_data_path: "/mnt/bmh01-rvmi/bcf-galaxy/centaurus/production/tool-data"
  - galaxy_new_file_path: "/mnt/rvmi/centaurus/galaxy/tmp"
  # Galaxy-specific Python installation
  - galaxy_python_version: "3.6.11"
  # Account management
  - allow_user_creation: no
  - allow_user_deletion: no
  - enable_require_login: yes
  - enable_user_activation: no
  # uWSGI sockets and ports
  - galaxy_http_port: "8080"
  - galaxy_uwsgi_socket: "4001"
  - galaxy_reports_uwsgi_socket: "9001"
  # Quotas
  - enable_quotas: yes
  # FTP upload
  - enable_ftp_upload: no
  # Reporting interface
  - enable_reports: yes
  # Welcome page etc
  - galaxy_welcome_template: "instances/centaurus/templates/{{ galaxy_name }}-welcome.html.j2"
  - galaxy_extra_static_content:
      - src: "instances/centaurus/files/centaurus_news.html"
        dest: "{{ galaxy_dir }}/{{ galaxy_clone_dir }}/static/centaurus_news.html"
  # uWSGI and handler configuration
  # Set number of uWSGI & handler processes in inventory file
  # Running jobs
  - galaxy_new_file_path: "/mnt/rvmi/centaurus/galaxy/tmp"
  # Check toolshed for updates
  - enable_tool_shed_check: yes
  # Centaurus-specific settings
  # Message of the day to display on the front page and message
  # to display under masthead
  # -- for ansible <2.6 "errors=..." option is not supported so
  #    an empty placeholder file is required to stop the playbook
  #    failing
  - centaurus_motd: "{{ lookup('file', 'instances/{{ galaxy_name }}/files/motd', errors='warn') }}"
  - galaxy_message: "{{ lookup('file', 'instances/{{ galaxy_name }}/files/message', errors='warn') }}"
  # Tools
  - galaxy_tool_conf_file: "instances/{{ galaxy_name }}/files/{{ galaxy_name }}-tool_conf.xml"

  vars_files:
  - instances/centaurus/{{ centaurus_secrets }}
  - instances/centaurus/galaxy_user.yml
  - instances/centaurus/custom_scss.yml
  - instances/centaurus/job_conf.yml
  - instances/centaurus/shed_tools.yml
  - instances/centaurus/local_tools.yml
  - instances/centaurus/resolvers.yml
  - instances/centaurus/tool_data.yml
  - instances/centaurus/sanitize_whitelist.yml

  roles:
  # Configure host VM
  - galaxy-user
  - epel-repo
  - nfslock
  - selinux
  - python3
  - nginx
  - postgresql
  - supervisord
  - role: postfix-null-client
    when: enable_smtp
  - certbot
  - role: jsedrop
    jsedrop_drop_dir: "{{ galaxy_jse_drop_dir }}"
    when: enable_local_jse_drop

  # Install and configure Galaxy
  - galaxy-utils
  - galaxy

  # Set up users, tools etc
  - galaxy-create-users
  - galaxy-install-tools
  - galaxy-set-default-quota