---
- hosts: cetus

  vars:
  # Host configuration
  - galaxy_user: "cetus-galaxy"
  - galaxy_uid: 22224
  - galaxy_group: "galaxy"
  - galaxy_gid: 400
  # Galaxy configuration
  - galaxy_name: "cetus"
  - galaxy_version: "release_19.09"
  - galaxy_install_dir: "/mnt/rvmi/cetus/galaxy"
  - galaxy_dir: "/mnt/rvmi/cetus/galaxy/teaching"
  # Database and reference data
  - galaxy_file_path: "/mnt/bmh01-rvmi/bcf-galaxy/cetus/teaching/database/files"
  - galaxy_job_working_dir: "/mnt/bmh01-rvmi/bcf-galaxy/cetus/teaching/job_working_directory"
  - galaxy_data_manager_data_path: "/mnt/bmh01-rvmi/bcf-galaxy/cetus/teaching/tool-data"
  # Galaxy-specific Python installation
  - galaxy_python_version: "3.6.11"
  # Account management
  - allow_user_creation: no
  - allow_user_deletion: no
  - enable_require_login: yes
  - enable_user_activation: no
  # Quotas
  - enable_quotas: yes
  # FTP upload
  - enable_ftp_upload: no
  # Reporting interface
  - enable_reports: yes
  # Welcome page etc
  - galaxy_welcome_template: "instances/cetus/templates/cetus-welcome.html.j2"
  # Custom colours
  - galaxy_custom_scss:
      # Colour for navbar/masthead
      - var: "brand-dark"
        value: "#660099"
      # Colour for text
      - var: "text-color"
        value: "#2c3143"
  # uWSGI and handler configuration
  # Set number of uWSGI & handler processes in inventory file
  # Running jobs
  - galaxy_new_file_path: "/mnt/rvmi/cetus/galaxy/tmp"
  # Check toolshed for updates
  - enable_tool_shed_check: yes
  # Cetus-specific settings
  # Message of the day to display on the front page and message
  # to display under masthead
  # -- for ansible <2.6 "errors=..." option is not supported so
  #    an empty placeholder file is required to stop the playbook
  #    failing
  - cetus_motd: "{{ lookup('file', 'instances/cetus/files/motd', errors='warn') }}"
  - galaxy_message: "{{ lookup('file', 'instances/cetus/files/message', errors='warn') }}"

  vars_files:
  - instances/cetus/{{ cetus_secrets }}

  roles:
  # Dependencies
  - galaxy-user
  - epel-repo
  - nfslock
  - selinux
  - python3
  - nginx
  - postgresql
  - proftpd
  - supervisord
  - role: postfix-null-client
    when: enable_smtp
  - certbot
  - role: jsedrop
    jsedrop_drop_dir: "{{ galaxy_jse_drop_dir }}"
    when: enable_local_jse_drop
  # Install and configure Galaxy
  - galaxy
  # Install utilities
  - galaxy-utils
  # Set up users, tools etc
  - galaxy-create-users
  - galaxy-install-tools
  - galaxy-set-default-quota
