# Create the 'galaxy' user and group (both with UID/GID of 400)

---
- hosts: '{{ hosts }}'
  tasks:
  - name: Create Galaxy group
    group:
      name=galaxy gid=400 state=present
    register: group_created

  - name: Create Galaxy user
    user:
      name=galaxy
      group=galaxy
      home=/home/galaxy
      uid=400
      state=present
    when: group_created | success
    register: user_created

# Need write permission on home so that static content
# can be read by Nginx proxy
- hosts: '{{ hosts }}'
  become_user: galaxy
  tasks:
  - name: Allow group read on Galaxy user home
    file:
      path=/home/galaxy
      mode='g+rx'
    when: user_created
    register: set_group_read_on_galaxy_home
