# Install, configure and start Nginx on remote server

---
# Set up Nginx
- hosts: '{{ hosts }}'
  tasks:
  - name: Install Nginx
    yum: name={{item}} state=present
    with_items:
    - nginx
    - libselinux-python
    - libsemanage-python
    register: nginx_installed
    notify:
    - Start Nginx

  - name: Set sebooleans for httpd
    seboolean:
      name={{ item }} state=yes persistent=yes
    with_items:
    - httpd_can_network_connect
    - httpd_enable_homedirs
    register: httpd_set_sebooleans
    notify:
    - Start Nginx

  - name: Allow httpd to network connect
    seboolean:
      name=httpd_can_network_connect state=yes persistent=yes
    register: httpd_set_sebooleans
    notify:
    - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started
