---
- hosts: '{{ hosts }}'
  vars:
  - galaxy_name: "palfinder"
  - galaxy_version: "v16.01"
  - galaxy_install_dir: "/home/galaxy/galaxies"
  - galaxy_server_name: "palfinder.ls.manchester.ac.uk"
  - default_quota_gb: 20
  - galaxy_python_dir: "/usr/local"
  vars_files:
  - palfinder_passwds.yml
  roles:
  - dependencies
  - galaxybase
  - palfinder
