---
- hosts: palfinder

  vars:
  # Ubuntu doesn't have Python2 by default
  # See e.g. https://www.toptechskills.com/ansible-tutorials-courses/how-to-fix-usr-bin-python-not-found-error-tutorial/
  - ansible_python_interpreter: /usr/bin/python3
  # Galaxy user and group on system
  - galaxy_user: "galaxy"
  - galaxy_uid: 400
  - galaxy_group: "galaxy"
  - galaxy_gid: 400
  # System Python and PostgreSQL versions
  - python_version: "3.10.5"
  - postgresql_version: "14"
  # Base installation directory
  - galaxy_install_dir: "/mnt/rvmi/palfinder/galaxy"
  # uWSGI and handler configuration
  - galaxy_uwsgi_processes: 8
  - galaxy_handler_processes: 1
  # Concurrent jobs
  - galaxy_registered_user_concurrent_jobs: 8
  - galaxy_unregistered_user_concurrent_jobs: 0
  - galaxy_concurrent_jobs: 8
  # SSL configuration
  # Enable/disable in inventory file (enable_https)
  # If enabled then will use the settings below
  - ssl_certificate: "/etc/letsencrypt/live/{{ galaxy_server_name }}/fullchain.pem"
  - ssl_certificate_key: "/etc/letsencrypt/live/{{ galaxy_server_name }}/privkey.pem"

  vars_files:
  - instances/palfinder/galaxy_config.yml
  - instances/palfinder/{{ palfinder_secrets }}
  - instances/palfinder/tools.yml
  - instances/palfinder/sanitize_whitelist.yml

  roles:
  # Configure host VM
  - galaxy-user
  - python3
  - nginx
  - postgresql
  - supervisord
  - certbot

  # Postfix mail client
  - role: postfix-null-client
    when: enable_smtp

  # Local JSEDrop service
  - role: jsedrop
    jsedrop_drop_dir: "{{ galaxy_jse_drop_dir }}"
    when: enable_local_jse_drop

  # Install and configure Galaxy
  - galaxy-utils
  - galaxy

  # Set up users, tools etc
  - galaxy-create-users
  - galaxy-install-tools
  - galaxy-set-default-quota

  # Additional set up
  - galaxy-add-library-data
  - galaxy-auto-delete-datasets
  - galaxy-audit-report
