---
- hosts: palfinder
  vars:
  - galaxy_name: "palfinder"
  - galaxy_version: "v16.01"
  - galaxy_install_dir: "/mnt/rvmi/palfinder/galaxy"
  - galaxy_server_name: "palfinder.ls.manchester.ac.uk"
  - galaxy_welcome_template: "roles/palfinder/templates/palfinder-welcome.html.j2"
  - galaxy_terms: "roles/palfinder/files/palfinder-terms.html"
  - galaxy_citations: "roles/palfinder/files/palfinder-citations.html"
  - galaxy_tool_conf_file: "roles/palfinder/files/palfinder-tool_conf.xml"
  - enable_require_login: yes
  - enable_user_activation: yes
  - enable_jse_drop: yes
  - galaxy_jse_drop_dir: "{{ galaxy_install_dir }}/palfinder/jse-drop-dpsf"
  - galaxy_default_runner: "jse_drop_default"
  - galaxy_job_destinations:
      - id: "jse_drop_default"
        runner: "jse_drop"
        jse_drop_dir: "{{ galaxy_jse_drop_dir }}"
        jse_drop_virtual_env: "{{ galaxy_root }}/.venv"
      - id: "jse_drop_8_cores"
        runner: "jse_drop"
        jse_drop_dir: "{{ galaxy_jse_drop_dir }}"
        jse_drop_virtual_env: "{{ galaxy_root }}/.venv"
        jse_drop_qsub_options: "-pe smp.pe 8"
        jse_drop_slots: "8"
  - galaxy_tool_destinations:
      - id: "trimmomatic"
        destination: "jse_drop_8_cores"
  - enable_quotas: yes
  - default_quota_gb: 20
  - delete_datasets_after: "30 days"
  - galaxy_python_dir: "/mnt/rvmi/palfinder/galaxy/python"
  - enable_reports: yes
  - enable_ftp_upload: yes
  - enable_smtp: yes
  - postfix_host_name: "{{ galaxy_server_name }}"
  - postfix_relay_host: "[smtp.manchester.ac.uk]"
  - galaxy_outgoing_email_addr: "Palfinder Galaxy <galaxy-no-reply@{{ galaxy_server_name  }}>"
  - galaxy_incoming_email_addr: "peter.briggs@manchester.ac.uk"
  - email_audit_report_to: "peter.briggs@manchester.ac.uk"
  - enable_https: yes
  - ssl_certificate: "/etc/letsencrypt/live/{{ galaxy_server_name }}/fullchain.pem"
  - ssl_certificate_key: "/etc/letsencrypt/live/{{ galaxy_server_name }}/privkey.pem"
  vars_files:
  - palfinder_passwds.yml
  roles:
  - dependencies
  - galaxybase
  - palfinder
