---
- hosts: palfinder

  vars:
  # Galaxy configuration
  - galaxy_name: "palfinder"
  - galaxy_version: "release_17.09"
  - galaxy_install_dir: "/mnt/rvmi/palfinder/galaxy"
  - galaxy_python_dir: "/mnt/rvmi/palfinder/galaxy/python"
  - enable_require_login: yes
  - enable_quotas: yes
  - enable_ftp_upload: yes
  # Welcome page etc
  - galaxy_welcome_template: "instances/palfinder/templates/palfinder-welcome.html.j2"
  - galaxy_terms: "instances/palfinder/files/palfinder-terms.html"
  - galaxy_citations: "instances/palfinder/files/palfinder-citations.html"
  # User manual
  - galaxy_extra_static_content:
      - src: "instances/palfinder/files/palfinder_galaxy_manual_v1.2.pdf"
        dest: "/usr/share/nginx/html/palfinder_galaxy_manual_v1.2.pdf"
        link: "/usr/share/nginx/html/manual"
  - galaxy_nginx_extra_locations:
      - location: "^~ /manual"
        alias: "/usr/share/nginx/html/manual"
        add_header: "Content-Type application/pdf"
  # uWSGI and handler configuration
  - galaxy_uwsgi_processes: 8
  - galaxy_handler_processes: 1
  # Users
  - galaxy_admin_user: "admin@galaxy.org"
  - galaxy_users:
      - email: "{{ galaxy_admin_user }}"
        password: "{{ galaxy_admin_passwd }}"
  # Tools
  - galaxy_tool_conf_file: "instances/palfinder/files/palfinder-tool_conf.xml"
  - galaxy_tools:
      - tool: "fastqc"
        owner: "devteam"
      - tool: "trimmomatic"
        owner: "pjbriggs"
      - tool: "pal_finder"
        owner: "pjbriggs"
  # Default quota
  - default_quota_gb: 20
  # Automatic dataset deletion
  - delete_datasets_after: "30 days"
  # Audit report
  - enable_reports: yes
  - email_audit_report_to: "peter.briggs@manchester.ac.uk"
  # Postfix/email configuration
  # Enable/disable in inventory file (enable_smtp)
  # If enabled then will use the settings below
  - postfix_host_name: "{{ galaxy_server_name }}"
  - postfix_relay_host: "[smtp.manchester.ac.uk]"
  - galaxy_outgoing_email_addr: "Palfinder Galaxy <galaxy-no-reply@{{ galaxy_server_name  }}>"
  - galaxy_incoming_email_addr: "peter.briggs@manchester.ac.uk"
  # SSL configuration
  # Enable/disable in inventory file (enable_https)
  # If enabled then will use the settings below
  - ssl_certificate: "/etc/letsencrypt/live/{{ galaxy_server_name }}/fullchain.pem"
  - ssl_certificate_key: "/etc/letsencrypt/live/{{ galaxy_server_name }}/privkey.pem"
  # Palfinder-specific settings
  # Message of the day to display on the front page
  - palfinder_motd:

  vars_files:
  - instances/palfinder/palfinder_passwds.yml

  roles:
  # Dependencies
  - galaxy-user
  - epel-repo
  - nfslock
  - python27
  - nginx
  - postgresql
  - proftpd
  - supervisord
  - role: postfix-null-client
    when: enable_smtp
  - lets-encrypt-client
  # Install Galaxy-specific Python 2.7
  - role: python27
    install_dir: "{{ galaxy_python_dir }}"
    become: yes
    become_user: "{{ galaxy_user }}"
  # Install and configure Galaxy
  - galaxy
  # Install utilities
  - galaxy-utils
  # Restart with master API key enabled (needed
  # to create user accounts)
  - role: restart-galaxy
    enable_master_api_key: yes
  - galaxy-create-users
  - galaxy-install-tools
  - galaxy-set-default-quota
  # Restart with master API key disabled
  - role: restart-galaxy
    enable_master_api_key: no
  # Additional set up
  - galaxy-add-library-data
  - galaxy-auto-delete-datasets
  - galaxy-audit-report
