# Build and install ProFTP on the remote host
# We need v1.3.5+ for PBKDF2 support
# See http://galacticengineer.blogspot.co.uk/2015/02/ftp-upload-to-galaxy-using-proftpd-and.html
---
- hosts: '{{ hosts }}'
  vars:
    proftpd_version: '1.3.5a'
  tasks:

  - name: Install ProFTPd build dependencies
    yum: state=present name={{item}}
    with_items:
    - postgresql-devel
    - openssl-devel
    register: installed_proftpd_dependencies

  - name: Download ProFTPd source
    get_url:
      url='https://github.com/proftpd/proftpd/archive/v{{ proftpd_version }}.tar.gz'
      dest=/root
    when: installed_proftpd_dependencies | success
    register: downloaded_proftpd_src

  - name: Unpack ProFTPd source
    unarchive:
      src='/root/proftpd-{{ proftpd_version }}.tar.gz'
      dest=/root
      copy=no
      owner=root
      group=root
      creates='/root/proftpd-{{ proftpd_version }}'
    when: downloaded_proftpd_src | success
    register: unpacked_proftpd_src

  - name: Install ProFTPd
    command:
      chdir='/root/proftpd-{{ proftpd_version }}'
      {{item}}
      creates=/usr/local/sbin/proftpd
    with_items:
    - ./configure --prefix=/usr/local --disable-auth-file --disable-ncurses --disable-ident --disable-shadow --enable-openssl --with-modules=mod_sql:mod_sql_postgres:mod_sql_passwd
    - make
    - make install
    when: unpacked_proftpd_src | success
    register: installed_proftpd
