# Set up Palfinder-specific Galaxy server

---
# Add master API key
- hosts: '{{ hosts }}'
  become_user: galaxy
  vars:
    - galaxy_root: /home/galaxy/galaxies/palfinder/galaxy
    - galaxy_admin_user: admin@galaxy.org
  tasks:
  - name: Install Nebulizer
    pip:
      name='https://github.com/pjbriggs/nebulizer/archive/v0.1.0.tar.gz'
      executable='{{ galaxy_root }}/.venv/bin/pip'
      extra_args='--no-binary :all:'
      state=present
    register: nebulizer_installed

  - name: Copy user and tool utility scripts
    copy:
      src={{ item }}
      dest='{{ galaxy_root }}/{{ item }}'
      mode='ugo+rx'
    with_items:
    - create_user.sh
    - install_tool.sh
    when: nebulizer_installed | success

  - name: Add master API key
    ini_file:
      dest='{{ galaxy_root }}/config/galaxy.ini'
      section='app:main' option='master_api_key' value={{ master_api_key }}
    when: nebulizer_installed | success
    register: added_master_api_key

  # Upload static pages (welcome, t&cs etc)
  - name: Upload static pages
    copy:
      src={{ item.src }}
      dest='{{ galaxy_root }}/static/{{ item.dest }}'
    with_items:
    - { src: 'palfinder-welcome.html', dest: 'welcome.html' }
    - { src: 'palfinder-terms.html', dest: 'terms.html' }
    when: added_master_api_key | success
    register: uploaded_static_content

  # Set configuration options specific to palfinder service
  - name: General Galaxy configuration
    ini_file:
      dest='{{ galaxy_root }}/config/galaxy.ini'
      section='app:main' option={{ item.option }} value={{ item.value }}
    with_items:
    - { option: 'brand', value: 'Microsat' }
    - { option: 'admin_users', value: '{{ galaxy_admin_user }}' }
    - { option: 'require_login', value: 'True' }
    - { option: 'enable_quotas', value: 'True' }
    - { option: 'welcome_url', value: '/static/welcome.html' }
    - { option: 'terms_url', value: '/static/terms.html' }
    when: uploaded_static_content | success
    register: configured_general_settings

# Update the tool_conf.xml to remove unwanted tools
  - name: Update tool_conf.xml
    copy:
      src=palfinder-tool_conf.xml
      dest='{{ galaxy_root}}/config/tool_conf.xml'
    when: added_master_api_key | success
    register: updated_tool_conf

# Restart Galaxy
- hosts: '{{ hosts }}'
  tasks:
  - name: Restart Galaxy with master API key
    supervisorctl:
      name='galaxy:'
      state=restarted
      supervisorctl_path=/usr/local/bin/supervisorctl
      config=/usr/local/etc/supervisord.conf
    when: updated_tool_conf | success
    register: restart_with_master_api_key

# Create admin user
- hosts: '{{ hosts }}'
  become_user: galaxy
  vars:
    - galaxy_root: /home/galaxy/galaxies/palfinder/galaxy
    - galaxy_admin_user: admin@galaxy.org
    - galaxy_admin_passwd: galaxyadmin
  tasks:
  - name: Create Galaxy admin user account
    command:
      chdir={{ galaxy_root }}
      {{ galaxy_root }}/create_user.sh {{ galaxy_admin_user }} {{ galaxy_admin_passwd }} {{ master_api_key }}
    when: restart_with_master_api_key
    register: created_admin_user

# Install tools
  - name: Install Galaxy tools
    command:
      chdir={{ galaxy_root }}
      {{ galaxy_root }}/install_tool.sh toolshed.g2.bx.psu.edu {{ item.tool }} {{ item.owner }} {{ master_api_key }}
    with_items:
    - { owner: 'devteam', tool: 'fastqc' }
    - { owner: 'pjbriggs', tool: 'trimmomatic' }
    - { owner: 'pjbriggs', tool: 'pal_finder' }
    when: created_admin_user | success
    register: installed_tools

# Remove master API key
  - name: Remove master API key
    ini_file:
      dest='{{ galaxy_root }}/config/galaxy.ini'
      section='app:main' option='master_api_key'
      state='absent'
    when: installed_tools | success
    register: removed_master_api_key

# Restart Galaxy
- hosts: '{{ hosts }}'
  tasks:
  - name: Restart Galaxy without master API key
    supervisorctl:
      name='galaxy:'
      state=restarted
      supervisorctl_path=/usr/local/bin/supervisorctl
      config=/usr/local/etc/supervisord.conf
    when: removed_master_api_key | success

