---
# General configuration

# Update the tool_conf.xml to remove unwanted tools
- name: Update tool_conf.xml
  copy:
    src=palfinder-tool_conf.xml
    dest='{{ galaxy_root}}/config/tool_conf.xml'

# Set the default quota
- name: Set default quota
  command:
    chdir={{ galaxy_root }}
    {{ galaxy_root }}/set_default_quota.sh {{ galaxy_db }} {{ galaxy_db_user }} {{ galaxy_db_password }} {{ default_quota_gb }}
