# Set up and populate data library with demo data
---
- name: Create and populate demo data library
  command:
    chdir={{ galaxy_root }}
    {{ galaxy_root }}/populate_data_library.sh {{ galaxy_admin_user }} {{ galaxy_admin_passwd }} "Example data/Fastqs" {{ item.file }} --file_type {{ item.type }}
  with_items:
  - { file: "{{ demo_data_dir }}/miseq_R1.fq", type: 'fastqsanger' }
  - { file: "{{ demo_data_dir }}/miseq_R2.fq", type: 'fastqsanger' }
  register: created_demo_library
