---
- include: set_facts.yml

- include: utils.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: configure.yml galaxy_url="{{ galaxy_url }}"
  become: yes
  become_user: "{{ galaxy_user }}"

- include: manual.yml

- include: restart.yml restart_with_master_api_key=yes

- include: adminuser.yml galaxy_url="{{ galaxy_url }}"
  become: yes
  become_user: "{{ galaxy_user }}"

- include: demodata.yml galaxy_url="{{ galaxy_url }}"
  become: yes
  become_user: "{{ galaxy_user }}"
  
- include: tools.yml galaxy_url="{{ galaxy_url }}"
  become: yes
  become_user: "{{ galaxy_user }}"

- include: deletedatasets.yml

- include: audit.yml

- include: restart.yml restart_without_master_api_key=yes
