---
- include: utils.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: configure.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: restart.yml restart_with_master_api_key=yes

- include: adminuser.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: demodata.yml
  become: yes
  become_user: "{{ galaxy_user }}"
  
- include: tools.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: deletedatasets.yml

- include: restart.yml restart_without_master_api_key=yes
