---
- include: utils.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: configure.yml
  become: yes
  become_user: "{{ galaxy_user }}"

# Add master API key
- name: Add master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key' value={{ master_api_key }}
  become: yes
  become_user: "{{ galaxy_user }}"
  register: added_master_api_key

# Restart Galaxy
- name: Restart Galaxy with master API key
  supervisorctl:
    name='galaxy:'
    state=restarted
    supervisorctl_path=/usr/local/bin/supervisorctl
    config=/usr/local/etc/supervisord.conf
  when: added_master_api_key | success

- include: adminuser.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: tools.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: deletedatasets.yml

# Remove master API key
- name: Remove master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key'
    state='absent'
  become: yes
  become_user: "{{ galaxy_user }}"
  register: removed_master_api_key

# Restart Galaxy
- name: Restart Galaxy without master API key
  supervisorctl:
    name='galaxy:'
    state=restarted
    supervisorctl_path=/usr/local/bin/supervisorctl
    config=/usr/local/etc/supervisord.conf
  when: removed_master_api_key | success
