# Restart Galaxy instance
---
# Add master API key
- name: Add master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key' value='{{ master_api_key }}'
  become: yes
  become_user: "{{ galaxy_user }}"
  when: restart_with_master_api_key == 'yes'
  register: added_master_api_key

# Remove master API key
- name: Remove master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key'
    state='absent'
  become: yes
  become_user: "{{ galaxy_user }}"
  when: restart_without_master_api_key == 'yes'
  register: removed_master_api_key

# Restart Galaxy
- name: Restart Galaxy
  supervisorctl:
    name='galaxy:'
    state=restarted
    supervisorctl_path=/usr/local/bin/supervisorctl
    config=/usr/local/etc/supervisord.conf
