# See https://galaxyproject.org/admin/config/performance/purge-histories-and-datasets/
---
- name: "Set up daily cron jobs to purge deleted data in Galaxy"
  cron:
    user: '{{ galaxy_user }}'
    name: '{{ item.name }}'
    job: ". {{ galaxy_root }}/.venv/bin/activate && sh {{ galaxy_root }}/scripts/cleanup_datasets/{{ item.script }}"
    hour: '{{ item.hour }}'
    minute: '{{ item.minute }}'
    state: present
  with_items:
    - { name: '{{ galaxy_name }} delete userless histories',
        script: 'delete_userless_histories.sh',
        hour: 03, minute: 00 }
    - { name: '{{ galaxy_name }} purge histories',
        script: 'purge_histories.sh',
        hour: 03, minute: 10 }
    - { name: '{{ galaxy_name }} purge libraries',
        script: 'purge_libraries.sh',
        hour: 03, minute: 20 }
    - { name: '{{ galaxy_name }} purge folders',
        script: 'purge_folders.sh',
        hour: 03, minute: 30 }
    - { name: '{{ galaxy_name }} delete datasets',
        script: 'delete_datasets.sh',
        hour: 03, minute: 40 }
    - { name: '{{ galaxy_name }} purge datasets',
        script: 'purge_datasets.sh',
        hour: 04, minute: 00 }

- name: "Clean up Galaxy job working directory"
  cron:
    user: '{{ galaxy_user }}'
    name: "{{ galaxy_name }} clean up files from job working directory"
    job: "{{ galaxy_dir }}/scripts/cleanup_dir.sh {{ galaxy_job_working_dir }} {{ galaxy_clean_up_cron_interval }}"
    special_time: 'daily'
    state: present

- name: "Clean up Galaxy temporary 'new file path'"
  cron:
    user: "{{ galaxy_user }}"
    name: "{{ galaxy_name }} clean up new file path directory"
    job: "{{ galaxy_dir }}/scripts/cleanup_dir.sh {{ galaxy_new_file_path }} {{ galaxy_clean_up_cron_interval }}"
    special_time: 'daily'
    state: present

- name: "Manage Galaxy SQL database backups"
  cron:
    user: "{{ galaxy_user }}"
    name: "{{ galaxy_name }} manage SQL database backups"
    job: "{{ galaxy_dir }}/scripts/manage_db_backups.sh {{ galaxy_dir }}/backups 8"
    special_time: 'weekly'
    state: present
