# Set up the Postgres Galaxy user and database
---
- name: Create PostgreSQL Galaxy user
  postgresql_user:
    name='{{ galaxy_db_user }}'
    password='{{ galaxy_db_password }}'
    role_attr_flags=NOSUPERUSER
    state=present
  register: postgresql_galaxy_user_created

- name: Create PostgreSQL Galaxy database
  postgresql_db:
    name='{{ galaxy_db }}'
    owner='{{ galaxy_db_user }}'
    state=present
  when: postgresql_galaxy_user_created is success
  register: postgresql_galaxy_db_created
