# Install dependencies
---
- name: "Install Galaxy system-package dependencies"
  yum:
    name:
      - 'python-psycopg2'
      - 'libtool'
      - 'libtool-ltdl'
      - 'libtool-ltdl-devel'
      - 'java-1.8.0-openjdk'
      - 'samtools'
      - 'python2-pyyaml'
      - 'net-tools'
      - 'hg'
      - 'libffi-devel'
      - 'ca-certificates'
    state: latest

- name: "Install system-package version of git"
  yum:
    name:
      - 'git'
    state: latest
  when: ansible_distribution_major_version != "6"

- name: "Install git from source into /usr/local"
  include_role:
    name: git
  vars:
    git_install_dir: '/usr/local'

- name: "Install gxctl.sh script"
  copy:
    src: 'gxctl.sh'
    dest: '{{ galaxy_utils_dir }}/bin/gxctl.sh'
    mode: 'ugo+rx'

- name: "Install Galaxy-specific Python 2.7"
  include_role:
    name: python27
  vars:
    python_version: "{{ galaxy_python_version }}"
    install_dir: "{{ galaxy_python_dir }}"
    ansible_become: yes
    ansible_become_user: "{{ galaxy_user }}"
  when: galaxy_python_version.startswith("2.7")

- name: "Install Galaxy-specific Python 3"
  include_role:
    name: python3
  vars:
    python_version: "{{ galaxy_python_version }}"
    install_dir: "{{ galaxy_python_dir }}"
    ansible_become: yes
    ansible_become_user: "{{ galaxy_user }}"
  when: galaxy_python_version.startswith("3.")
