# Install dependencies
---
- name: "Install Galaxy system-package dependencies"
  yum:
    name:
      - 'python-psycopg2'
      - 'libtool'
      - 'libtool-ltdl'
      - 'libtool-ltdl-devel'
      - 'java-1.8.0-openjdk'
      - 'samtools'
      - 'python2-pyyaml'
      - 'net-tools'
      - 'hg'
    state: latest

- name: "Install git"
  yum:
    name:
      - 'git'
    state: latest
  when: ansible_distribution_major_version != "6"

- name: "Install galaxyctl.sh script"
  copy:
    src: 'galaxyctl.sh'
    dest: '{{ galaxy_utils_dir }}/bin/galaxyctl.sh'
    mode: 'ugo+rx'
