# Stop Galaxy running
---
- name: "Command to halt running Galaxy"
  debug:
    msg: "{{ galaxy_utils_dir }}/bin/galaxyctl.sh stop {{ galaxy_name }}"

- name: "Halt running Galaxy"
  command:
    "{{ galaxy_utils_dir }}/bin/galaxyctl.sh stop {{ galaxy_name }}"
