---
# Import the code for the JSE-drop job runner plugin
- name: Import the JSE-drop job runner plugin files
  copy:
    dest='{{ galaxy_root }}/lib/galaxy/jobs/runners/{{ item }}'
    src='{{ item }}'
  with_items:
  - jse_drop.py
  - jse_drop_runner.py

# Create the JSE-drop directory
- name: Create JSE-drop directory
  file:
    path='{{ galaxy_jse_drop_dir }}'
    state=directory
    mode=0775

- name: "Clean up files from JSE-drop directory marked for clean up"
  cron:
    user='{{ galaxy_user }}'
    name='Clean up JSE-drop jobs marked for clean up or as deleted'
    minute='*/5'
    job='/usr/local/bin/python3 {{ galaxy_root }}/lib/galaxy/jobs/runners/jse_drop.py {{ galaxy_jse_drop_dir }} --clean {{ galaxy_jse_drop_cleanup_grace_period }} 2>&1 1>>{{ galaxy_log_dir}}/jse_drop_cleanup.log'
    state=present

- name: "Clean up old jobs from JSE-drop directory"
  cron:
    user='{{ galaxy_user }}'
    name='Clean up old JSE-drop jobs'
    special_time='daily'
    job='/usr/local/bin/python3 {{ galaxy_root }}/lib/galaxy/jobs/runners/jse_drop.py {{ galaxy_jse_drop_dir }} -s all --clean "{{ galaxy_clean_up_cron_interval }} days" 2>&1 1>>{{ galaxy_log_dir}}/jse_drop_cleanup.log'
    state=present
