---
# Import the code for the JSE-drop job runner plugin
- name: Import the JSE-drop job runner plugin files
  copy:
    dest='{{ galaxy_root }}/lib/galaxy/jobs/runners/{{ item }}'
    src='{{ item }}'
  with_items:
  - jse_drop.py
  - jse_drop_runner.py

# Create the JSE-drop directory
- name: Create JSE-drop directory
  file:
    path='{{ galaxy_jse_drop_dir }}'
    state=directory
    mode=0775

# Setup cron jobs to clean up JSE-drop directory
- name: Clean up qsub files from JSE-drop directory
  cron:
    user='{{ galaxy_user }}'
    name='Remove old JSE-drop .qsub files'
    hour=05
    minute=00
    job='find {{ galaxy_jse_drop_dir }} -name "*.qsub" -type f -mtime +{{ galaxy_clean_up_cron_interval }} -exec rm -f {} \;'
    state=present

- name: Clean up other files from JSE-drop directory
  cron:
    user='{{ galaxy_user }}'
    name='Remove all other old JSE-drop files'
    hour=05
    minute=00
    job='find {{ galaxy_jse_drop_dir }} -name "*" -type f -mtime +{{ galaxy_clean_up_cron_interval }} -exec rm -f {} \;'
    state=present

- name: "Clean up files from JSE-drop directory marked for clean up"
  cron:
    user='{{ galaxy_user }}'
    name='Clean up JSE-drop jobs marked for clean up'
    minute='*/5'
    job='. {{ galaxy_root }}/.venv/bin/activate && PYTHONPATH={{ galaxy_root }}/lib:$PYTHONPATH python -c "from galaxy.jobs.runners.jse_drop import jse_drop_cleanup ; jse_drop_cleanup(\'{{ galaxy_jse_drop_dir }}\',interval={{ galaxy_jse_drop_cleanup_grace_period }})" 2>&1 1>>{{ galaxy_log_dir}}/jse_drop_cleanup.log'
    state=present
