---

- include: halt_galaxy.yml

- include: remove_legacy_artefacts.yml

- include: "dependencies_ubuntu.yml"

- name: "Install Galaxy-specific Python"
  include_role:
    name: python3
  vars:
    python_version: "{{ galaxy_python_version }}"
    install_dir: "{{ galaxy_python_dir }}"
    ansible_become: yes
    ansible_become_user: "{{ galaxy_user }}"

- include: database.yml
  become: yes
  become_user: postgres

- include: galaxy.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: galaxy_service.yml

- include: reports.yml
  when: enable_reports

- include: jsedrop.yml
  when: enable_jse_drop
  become: yes
  become_user: "{{ galaxy_user }}"

- include: cleanup.yml

- include: logrotate.yml

- include: nginxproxy.yml

- include: static.yml
  when: galaxy_extra_static_content|default(None) != None

- include: cronvars.yml
  when: enable_smtp

- include: start_galaxy.yml
