---
- include: dependencies.yml

- include: database.yml
  become: yes
  become_user: postgres

- include: galaxy.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: static.yml
  when: galaxy_extra_static_content|default(None) != None

- include: reports.yml
  when: enable_reports

- include: purgehistories.yml

- include: logrotate.yml

- include: ftpupload.yml
  when: enable_ftp_upload

- include: uwsgi.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: supervisor.yml

- include: nginxproxy.yml
