---
- name: Set up cron jobs to purge deleted data
  cron:
    user='{{ galaxy_user }}'
    name='{{ item.name }}'
    job=". {{ galaxy_root }}/.venv/bin/activate && sh {{ galaxy_root }}/scripts/cleanup_datasets/{{ item.script }}"
    weekday=00 hour=03 minute=00
    state=present
  with_items:
  - { name: 'Delete userless histories', script: 'delete_userless_histories.sh' }
  - { name: 'Purge histories', script: 'purge_histories.sh' }
  - { name: 'Purge libraries', script: 'purge_libraries.sh' }
  - { name: 'Purge folders', script: 'purge_folders.sh' }
  - { name: 'Delete datasets', script: 'delete_datasets.sh' }
  - { name: 'Purge datasets', script: 'purge_datasets.sh' }
