# Install Python for Galaxy
---
- name: "Install Galaxy-specific Python 2.7"
  include_role:
    name: python27
  vars:
    python_version: "{{ galaxy_python_version }}"
    install_dir: "{{ galaxy_python_dir }}"
    ansible_become: yes
    ansible_become_user: "{{ galaxy_user }}"
  when: galaxy_python_version.startswith("2.7")

- name: "Install Galaxy-specific Python 3"
  include_role:
    name: python3
  vars:
    python_version: "{{ galaxy_python_version }}"
    install_dir: "{{ galaxy_python_dir }}"
    ansible_become: yes
    ansible_become_user: "{{ galaxy_user }}"
  when: galaxy_python_version.startswith("3.")
