# Remove 'legacy' artefacts, configs, cron jobs etc set up pre-22.01
# These will be replaced by instance-specific versions
---
# Logrotation file
- name: "Remove legacy logrotation file"
  file:
    path: '/etc/logrotate.d/galaxy'
    state: absent

# Cron jobs
- name: "Remove legacy cron jobs for Galaxy"
  cron:
    user: '{{ galaxy_user }}'
    name: '{{ item }}'
    state: absent
  with_items:
    - 'Delete userless histories'
    - 'Purge histories'
    - 'Purge libraries'
    - 'Purge folders'
    - 'Delete datasets'
    - 'Purge datasets'
    - 'Clean up files from job working directory'
    - 'Clean up empty directories from job working directory'
    - 'Delete old datasets'
    - 'Email audit report'
    - 'Clean up deleted files from JSE-drop directory'
    - 'Remove JSE-drop jobs marked for clean up or as deleted'
    - 'Delete old FTP files'

# NB using certbot SSL certificate renewal is performed automatically
# so this task simply removes any existing legacy cronjob
- name: "Remove legacy cron job for SSL certificate renewal"
  cron:
    user="root"
    name="Renew SSL certificate from Lets Encrypt"
    state=absent

# Remove Galaxy Python (if requested)
- name: "Remove Galaxy Python installation"
  file:
    path: '{{ galaxy_python_dir }}'
    state: absent
  when: galaxy_force_reinstall_python == True

# Remove Galaxy virtualenv (if requested)
- name: "Remove Galaxy virtual env"
  file:
    path: '{{ galaxy_root }}/.venv'
    state: absent
  when: galaxy_force_reinstall_venv == True

# Remove artefacts (utilities, configs etc) from previous Galaxy
# versions
- name: "Remove artefacts from previous Galaxy versions"
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ galaxy_utils_dir }}/bin/gxctl.sh'
    - '/usr/local/etc/supervisord.d/{{ galaxy_name }}.ini'
