# Remove 'legacy' artefacts and cron jobs set up pre-19.09
# These will be replaced by instance-specific versions
---
# Logrotation file
- name: "Remove legacy logrotation file"
  file:
    path: '/etc/logrotate.d/galaxy'
    state: absent

# Cron jobs
- name: "Remove legacy cron jobs for Galaxy"
  cron:
    user: '{{ galaxy_user }}'
    name: '{{ item }}'
    state: absent
  with_items:
    - 'Delete userless histories'
    - 'Purge histories'
    - 'Purge libraries'
    - 'Purge folders'
    - 'Delete datasets'
    - 'Purge datasets'
    - 'Clean up files from job working directory'
    - 'Clean up empty directories from job working directory'
    - 'Delete old datasets'
    - 'Email audit report'

# NB using certbot SSL certificate renewal is performed automatically
# so this task simply removes any existing legacy cronjob
- name: "Remove legacy cron job for SSL certificate renewal"
  cron:
    user="root"
    name="Renew SSL certificate from Lets Encrypt"
    state=absent

# Remove Python
- name: "Remove Galaxy Python installation"
  file:
    path: '{{ galaxy_python_dir }}'
    state: absent
  when: galaxy_force_reinstall_python == True

# Remove Galaxy virtualenv
- name: "Remove Galaxy virtual env"
  file:
    path: '{{ galaxy_root }}/.venv'
    state: absent
  when: galaxy_force_reinstall_venv == True
