# Automatically renew SSL certificates
---
- name: "Set up automatic SSL certificate renewal"
  block:
    - name: "Get random minute in the hour for certificate renewal"
      set_fact:
        random_minute: "{{ 59 | random }}"
      run_once: yes

    - name: "Cronjob to renew SSL certificates automatically"
      cron:
        user="root"
        name="Renew SSL certificate from Lets Encrypt"
        job='export PATH={{ galaxy_python_dir }}/bin:$PATH && /usr/local/bin/certbot-auto renew --deploy-hook "/sbin/service nginx reload" >> /var/log/le-renew'
        hour=2
        minute="{{ random_minute }}"
        weekday=1
        state=present
  when: enable_https and enable_certificate_renewal

- name: "Remove cronjob for SSL certificate renewal"
  cron:
    user="root"
    name="Renew SSL certificate from Lets Encrypt"
    state=absent
  when: not enable_https or not enable_certificate_renewal
