# Enable Galaxy's reporting interface
---
- name: Copy sample Galaxy reports.ini configuration file
  command:
    chdir='{{ galaxy_root }}/config'
    cp reports.ini.sample reports.ini
    creates='{{ galaxy_root }}/config/reports.ini'

- name: Create Galaxy reports configuration file
  command:
    chdir='{{ galaxy_root }}/config'
    cp reports.ini.sample reports.ini
    creates='{{ galaxy_root }}/config/reports.ini'

- name: Configure Galaxy reports server settings
  ini_file:
    dest='{{ galaxy_root }}/config/reports.ini'
    section='server:main' option={{ item.option }} value={{ item.value }}
  with_items:
  - { option: 'use', value: 'egg:Paste#http' }
  - { option: 'port', value: '9001' }
  - { option: 'host', value: '127.0.0.1' }
  - { option: 'use_threadpool', value: 'true' }
  - { option: 'threadpool_workers', value: '10' }
  notify: Restart Galaxy reports

- name: Configure Galaxy reports app settings
  ini_file:
    dest='{{ galaxy_root }}/config/reports.ini'
    section='app:main' option={{ item.option }} value={{ item.value }}
  with_items:
  - { option: 'paste.app_factory', value: 'galaxy.webapps.reports.buildapp:app_factory' }
  - { option: 'database_connection', value: 'postgres://{{ galaxy_db_user }}:{{ galaxy_db_password }}@localhost:5432/{{ galaxy_db }}' }
  - { option: 'file_path', value: '{{ galaxy_file_path }}' }
  - { option: 'filter-with', value: 'proxy-prefix' }
  - { option: 'cookie_path', value: '/reports' }
  notify: Restart Galaxy reports

- name: Set GDPR compliance mode
  ini_file:
    dest='{{ galaxy_root }}/config/reports.ini'
    section='app:main' option='enable_beta_gdpr' value='{{ enable_beta_gdpr }}'

- name: Configure Galaxy reports proxy settings
  ini_file:
    dest='{{ galaxy_root }}/config/reports.ini'
    section='filter:proxy-prefix'
    option={{ item.option }} value={{ item.value }}
  with_items:
  - { option: 'use', value: 'egg:PasteDeploy#prefix' }
  - { option: 'prefix', value: '/reports' }
  -  notify: Restart Galaxy reports

