# Enable Galaxy's reporting interface
---
- name: Check for sample reports.yml configuration file
  stat:
    path: '{{ galaxy_root }}/config/reports.yml.sample'
  register: reports_yml

- name: Create reports.yml configuration file
  include: reports_yaml.yml
  when: reports_yml.stat.exists == True
  become: yes
  become_user: '{{ galaxy_user }}'

- name: Check for sample reports.ini configuration file
  stat:
    path: '{{ galaxy_root }}/config/reports.ini.sample'
  register: reports_ini

- name: Create reports.ini configuration file
  include_tasks: reports_ini.yml
  when: reports_ini.stat.exists == True
  become: yes
  become_user: '{{ galaxy_user }}'

# Remove old init.d script
- name: Check for init.d script for reports
  stat:
    path: '/etc/init.d/galaxy_reports'
  register: reports_init_script

- name: Stop Galaxy reports service
  service:
    name=galaxy_reports
    enabled=false
    state=stopped
  when: reports_init_script.stat.exists == True

- name: Remove init.d script for reports
  file:
    path='/etc/init.d/galaxy_reports'
    state=absent
  when: reports_init_script.stat.exists == True

# Set up Nginx proxy password protection
- name: Set up Galaxy reports access
  htpasswd:
    path={{ galaxy_reports_htpasswd }}
    name={{ galaxy_reports_user }}
    password={{ galaxy_reports_password }}
    owner=root
    group=root
    mode=0644
    create=yes
