# Enable Galaxy's reporting interface
---
- name: Create reports.yml configuration file
  template:
    dest='{{ galaxy_root }}/config/reports.yml'
    src=galaxy-reports.yml.j2
  become: yes
  become_user: '{{ galaxy_user }}'

# Remove old init.d script
- name: Check for init.d script for reports
  stat:
    path: '/etc/init.d/galaxy_reports'
  register: reports_init_script

- name: Stop Galaxy reports service
  service:
    name=galaxy_reports
    enabled=false
    state=stopped
  when: reports_init_script.stat.exists == True

- name: Remove init.d script for reports
  file:
    path='/etc/init.d/galaxy_reports'
    state=absent
  when: reports_init_script.stat.exists == True

# Set up Nginx proxy password protection
- name: Set up Galaxy reports access
  htpasswd:
    path={{ galaxy_reports_htpasswd }}
    name={{ galaxy_reports_user }}
    password={{ galaxy_reports_password }}
    owner=root
    group=root
    mode=0644
    create=yes
