# Install and configure uWSGI and set up handlers
# See https://wiki.galaxyproject.org/Admin/Config/Performance/Scaling#uWSGI
---

- name: Configure Galaxy uWSGI settings
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='uwsgi' option='{{ item.option }}' value='{{ item.value }}'
  with_items:
  - { option: 'processes', value: '{{ galaxy_uwsgi_processes }}' }
  - { option: 'stats', value: '127.0.0.1:9191' }
  - { option: 'socket', value: '127.0.0.1:4001' }
  - { option: 'pythonpath', value: 'lib' }
  - { option: 'threads', value: '4' }
  - { option: 'logto', value: '{{ galaxy_log_dir }}/uwsgi.log' }
  - { option: 'master', value: 'True' }

- name: Configure Galaxy uWSGI settings in app-main
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='{{ item.option }}' value='{{ item.value }}'
  with_items:
  - { option: 'static_enabled', value: 'False' }
  - { option: 'track_jobs_in_database', value: 'True' }
