---
# Install, configure and start Supervisord

- include: "dependencies_redhat.yml"
  when: ansible_distribution == "Scientific" or ansible_distribution == "CentOS"

- include: "dependencies_ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- name: "Check if Supervisor is already installed"
  stat:
    path: "{{ supervisor_install_dir }}/bin/supervisord"
  register: supervisord

- name: "Determine if Supervisor should be installed"
  set_fact:
    install_supervisor: "{{ not supervisord.stat.exists }}"

- name: "Determine if Supervisor should be reinstalled"
  block:
  - name: "Get installed Supervisor version"
    shell:
      "{{ supervisor_install_dir }}/bin/supervisord --version"
    register: supervisord_installed_version

  - name: "Check if new version is different"
    set_fact:
      install_supervisor: "{{ supervisord_installed_version.stdout is version(supervisor_version,'!=') }}"

  - name: "Report Supervisord versions"
    debug:
      msg: "Supervisord: current version {{ supervisord_installed_version.stdout }} -> {{ supervisor_version }}"
  when: supervisord.stat.exists

- name: "Build and install local version of Supervisor"
  block:
  - name: "Disable Supervisord service"
    service:
      name: 'supervisord'
      enabled: false
      state: stopped
    when: supervisord.stat.exists

  - name: "Determine the user home directory"
    shell:
      "echo $HOME"
    register: user_home
    changed_when: False

  - name: "Determine the build directory"
    set_fact:
      build_dir: "{{ user_home.stdout }}/build"

  - name: "Print the location of the build directory"
    debug: msg="Build directory {{ build_dir }}"

  - name: "Create build directory"
    file:
      path: '{{ build_dir }}'
      state: directory

  - name: "Download Supervisor source"
    get_url:
      url: 'https://github.com/Supervisor/supervisor/archive/{{ supervisor_version }}.tar.gz'
      dest: '{{ build_dir }}/supervisor-{{ supervisor_version }}.tar.gz'

  - name: "Unpack Supervisor source"
    unarchive:
      src: '{{ build_dir }}/supervisor-{{ supervisor_version }}.tar.gz'
      dest: '{{ build_dir }}'
      copy: no
      owner: root
      group: root
      creates: '{{ build_dir }}/supervisor-{{ supervisor_version }}'

  - name: "Install Supervisor"
    command:
      chdir: '{{ build_dir }}/supervisor-{{ supervisor_version }}'
      cmd: "{{ supervisor_python_exe }} setup.py install --prefix={{ supervisor_install_dir }}"

  - name: "Create Supervisord conf file"
    shell: >-
      {{ supervisor_install_dir }}/bin/echo_supervisord_conf > {{ supervisor_install_dir }}/etc/supervisord.conf
      creates={{ supervisor_install_dir }}/etc/supervisord.conf
    notify: "Restart supervisord.service"

  - name: "Create supervisord.d directory"
    file:
      path: '{{ supervisor_install_dir }}/etc/supervisord.d'
      state: directory

  - name: "Create supervisord log directory"
    file:
      path: '/var/log/supervisord'
      state: directory

  - name: "Update Supervisord conf file"
    ini_file:
      dest: '{{ supervisor_install_dir }}/etc/supervisord.conf'
      section: '{{ item.section }}'
      option: '{{ item.option }}'
      value: '{{ item.value }}'
    with_items:
      - section: 'supervisord'
        option: 'logfile'
        value: '/var/log/supervisord/supervisord.log'
      - section: 'supervisord'
        option: 'pidfile'
        value: '/var/run/supervisord.pid'
      - section: 'include'
        option: 'files'
        value: '/usr/local/etc/supervisord.d/*.ini'
    notify: "Restart supervisord.service"
  when: install_supervisor == True

- include: "supervisord_initd.yml"
  when: ansible_distribution == "Scientific" or ansible_distribution == "CentOS"

- include: "supervisord_service.yml"
  when: ansible_distribution == "Ubuntu"
