---
- name: "Install Supervisord init.d script"
  block:
    - name: "Check existence of Supervisord init.d script"
      stat:
        path: "/etc/init.d/supervisord"
      register: init_d

    - name: "Create init.d script for Supervisord"
      copy:
        dest: '/etc/init.d/supervisord'
        src: 'supervisord.init.sh'
        mode: 'ugo+x'
      when: not init_d.stat.exists
      notify: "Restart supervisord.service"
  when: install_supervisor == True

- name: "Start Supervisord service via init.d script"
  service:
    name: 'supervisord'
    enabled: on
    state: started
