---
- name: "Create service file for Supervisord"
  template:
    src: 'supervisord.service.j2'
    dest: '/lib/systemd/system/supervisord.service'
  notify: "Restart supervisord.service"
  when: install_supervisor == True

- name: "Start Supervisord service"
  systemd:
    name: 'supervisord'
    enabled: on
    state: restarted