---
# Automatic deletion of datasets older than certain age

- name: Set up cron jobs to delete old datasets
  cron:
    user="{{ galaxy_user }}"
    name="Delete old datasets"
    job="{{ galaxy_utils_dir }}/bin/delete_old_datasets.sh {{ galaxy_db }} {{ galaxy_db_user }} {{ galaxy_db_password }} '{{ delete_datasets_after }}' >> {{ galaxy_dir }}/logs/delete_datasets.log"
    hour=23 minute=00
    state=present
