---
# Defaults for user account creation

# galaxy-utils should be installed under the 'bin' subdirectory
# of this location
galaxy_utils_dir: "/usr/local"

# User accounts to be created
# If defined then should be a list e.g.
# galaxy_users:
#      - email: "{{ galaxy_admin_user }}"
#        password: "{{ galaxy_admin_passwd }}"
#      - email: ...
#      - password: ...etc
galaxy_users: null

# Postgresql database
galaxy_db: "galaxy_{{ galaxy_name }}"
galaxy_db_user: "{{ galaxy_user }}"
galaxy_db_password: "{{ galaxy_db_user }}"

# Is https enabled
enable_https: no

# Galaxy proxy prefix
galaxy_proxy_prefix:

# Is user activation enable?
enable_user_activation: no
