---
# Restart Galaxy instance (with/without master API key)

- name: Add master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key' value='{{ master_api_key }}'
  become: yes
  become_user: "{{ galaxy_user }}"
  when: enable_master_api_key

- name: Remove master API key
  ini_file:
    dest='{{ galaxy_root }}/config/galaxy.ini'
    section='app:main' option='master_api_key'
    state='absent'
  become: yes
  become_user: "{{ galaxy_user }}"
  when: not enable_master_api_key

- name: Restart Galaxy
  command:
    "{{ galaxy_utils_dir }}/bin/restart_galaxy.sh galaxy"
