---
# Restart Galaxy instance (with/without master API key)

- name: "Restart Galaxy with master API key"
  command:
    "{{ galaxy_utils_dir }}/bin/galaxyctl.sh restart {{ galaxy_name }} -c {{ galaxy_root }}/config/galaxy.yml -u {{ galaxy_user }} --master-api-key {{ master_api_key }}"
  when: enable_master_api_key

- name: "Restart Galaxy without master API key"
  command:
    "{{ galaxy_utils_dir }}/bin/galaxyctl.sh restart {{ galaxy_name }} -c {{ galaxy_root }}/config/galaxy.yml -u {{ galaxy_user }} --no-master-api-key"
  when: not enable_master_api_key
