---
# Restart Galaxy instance (with/without master API key)

- name: Add master API key to Galaxy config file
  lineinfile:
    path: '{{ galaxy_root }}/config/galaxy.yml'
    regexp: "(#?)master_api_key: (.*)"
    line: "  master_api_key: {{ master_api_key }}"
  become: yes
  become_user: "{{ galaxy_user }}"
  when: enable_master_api_key == True

- name: Remove master API key from Galaxy config file
  lineinfile:
    path: '{{ galaxy_root }}/config/galaxy.yml'
    regexp: "(#?)master_api_key: (.*)"
    line: "  #master_api_key: changethis"
  become: yes
  become_user: "{{ galaxy_user }}"
  when: enable_master_api_key == False

- name: Restart Galaxy
  command:
    "{{ galaxy_utils_dir }}/bin/restart_galaxy.sh galaxy"
