---
# Install JSEDrop service via systemd
  
- name: "Create service file for jsedrop.service"
  template:
    src="jsedrop.service.j2"
    dest="/lib/systemd/system/jsedrop.service"
  notify:
    - "Restart jsedrop.service"

- name: "(Re)start jsedrop.service using systemd"
  systemd:
    name="jsedrop"
    enabled=yes
    state=restarted
