---
# Install jsedrop.py as a service on the remote host

- name: "Install jsedrop.py"
  copy:
    src="jsedrop.py"
    dest="{{ jsedrop_install_dir }}/jsedrop.py"
    mode="ugo+x"

- name: "Create service file for jsedrop.service"
  template:
    src="jsedrop.service.j2"
    dest="/lib/systemd/system/jsedrop.service"
  notify:
    - "Restart jsedrop.service"

- name: "(Re)start jsedrop.service using systemd"
  systemd:
    name="jsedrop"
    enabled=yes
    state=restarted
