---
# Install jsedrop.py as a service on the remote host

- name: "Install jsedrop.py"
  copy:
    src="jsedrop.py"
    dest="{{ jsedrop_install_dir }}/jsedrop.py"
    mode="ugo+x"

- include: "jsedrop_initd.yml"
  when: ansible_distribution == "Scientific" and ansible_distribution_major_version == "6"

- include: "jsedrop_service.yml"
  when: (ansible_distribution == "Scientific" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "7"

- include: "jsedrop_service.yml"
  when: ansible_distribution == "Ubuntu"

