# Build and install ProFTP on the remote host
# We need v1.3.5+ for PBKDF2 support
# See http://galacticengineer.blogspot.co.uk/2015/02/ftp-upload-to-galaxy-using-proftpd-and.html
---
- name: Install ProFTPd build dependencies
  yum: state=present name={{item}}
  with_items:
  - gcc
  - postgresql-devel
  - openssl-devel
  - pam-devel
  - libnetfilter_conntrack

- name: Determine the user home directory
  shell:
    "echo $HOME"
  register: user_home

- name: Determine the build directory
  set_fact:
    build_dir: "{{ user_home.stdout }}/build"

- name: Print the location of the build directory
  debug: msg="Build directory {{ build_dir }}"

- name: Create build directory
  file:
    path='{{ build_dir }}'
    state=directory

- name: Download ProFTPd source
  get_url:
    url='https://github.com/proftpd/proftpd/archive/v{{ proftpd_version }}.tar.gz'
    dest='{{ build_dir }}'

- name: Unpack ProFTPd source
  unarchive:
    src='{{ build_dir }}/proftpd-{{ proftpd_version }}.tar.gz'
    dest='{{ build_dir }}'
    copy=no
    owner=root
    group=root
    creates='{{ build_dir }}/proftpd-{{ proftpd_version }}'

- name: Install ProFTPd
  command:
    chdir='{{ build_dir }}/proftpd-{{ proftpd_version }}'
    {{item}}
    creates={{ proftpd_install_dir }}/sbin/proftpd
  with_items:
  - ./configure --prefix={{ proftpd_install_dir }} --disable-auth-file --disable-ncurses --disable-ident --disable-shadow --enable-openssl --with-modules=mod_sql:mod_sql_postgres:mod_sql_passwd
  - make
  - make install

# Set up as a service
- name: Create init.d script for ProFTPd
  copy:
    dest=/etc/init.d/proftpd
    src=proftpd.init.sh
    mode='ugo+x'

- name: Start ProFTPd service
  service:
    name=proftpd
    enabled=on
    state=started

