---
# Create user accounts in Galaxy instance

- name: Set Galaxy URL
  set_fact:
    galaxy_url: "{{ 'https' if enable_https else 'http' }}://{{ galaxy_server_name }}{{ galaxy_proxy_prefix }}/"

- name: Create Galaxy user accounts
  command:
    "{{ galaxy_utils_dir }}/bin/create_user.sh '{{ item.email }}' '{{ item.password }}' '{{ master_api_key }}' '{{ galaxy_url }}'"
  with_items: "{{ galaxy_users }}"
  when: galaxy_users|default(None) != None

# Activate the admin user account
- name: Activate Galaxy user accounts
  command:
    "{{ galaxy_utils_dir }}/bin/activate_user.sh '{{ galaxy_db }}' '{{ galaxy_db_user }}' '{{ galaxy_db_password }}' '{{ item.email }}'"
  with_items: "{{ galaxy_users }}"
  become: yes
  become_user: "{{ galaxy_user }}"
  when: galaxy_users|default(None) != None and enable_user_activation

