---
# Defaults for tool installation into Galaxy

# NB the following variables need to be set
# externally for this task:
#
# - galaxy_name
# - galaxy_root (or galaxy_dir)
# - galaxy_user
# - master_api_key

# galaxy-utils should be installed under the 'bin' subdirectory
# of this location
galaxy_utils_dir: "/usr/local"

# Tools to be installed from the main toolshed
# If defined then should be a list e.g.
# galaxy_tools:
#      - tool: "column_maker"
#        owner: "devteam"
#        section: "Text Manipulation"
#      - tool: ...
#        owner: ...
#        section: ... etc
galaxy_tools: null

# Local tools to be installed
# If defined then should be a list e.g.
# local_galaxy_tools:
#      - name: "venn_diagram"
#        tool_files:
#          - "tools/venn_diagram/cistrome_venn_diagram.xml"
#          - "tools/venn_diagram/cistrome_venn_diagram.py"
#        section:
#          name: "ChIP-seq"
#          id: "ngs-chip-seq"
#      - name: ...
#        tool_files:
#          - ... etc
# NB the 'section' is optional; if omitted then the tool
# will appear in the top-level of the tool panel
local_galaxy_tools: null

# References to local tools which are managed outside
# the Ansible playbooks
# These will be added to the tool config XML
# If defined then should be a list e.g.
# local_galaxy_tool_references:
#      - name: "cas13_design"
#        tool_xml_files:
#          - "tools/cas13_design/RfxCas13d_GuideScoring.xml"
#          - "tools/cas13_design/guide_specificity_metrics.xml"
#          - "tools/cas13_design/pdf_report.xml"
#        section:
#          name: "Cas13 Guide Design"
#          id: "cas13-guide-design"
#      - name: ...
#        tool_files:
#          - ... etc
local_galaxy_tool_references: null

# Data tables
# If defined then should be a list e.g.
# galaxy_tool_data_tables:
#      - description: "Annotation databases for CEAS"
#        name: "ceas_annotations"
#        columns: "value, dbkey, name, path"
#        file_path: "tool-data/ceas.loc"
#      - description: ...
#        name: ...
#        columns: ...
#        file_path: ...
galaxy_tool_data_tables: null

# Reference data for tool .loc files
#
# Define additional entries for .loc files as a
# dictionary with:
# - loc_file (name of the .loc file, relative to tool-data)
# - data     (data to add)
#
# For example:
#
# galaxy_loc_file_data:
#     - loc_file: "alignseq.loc"
#       data:
#         - "seq\thg38\t/mnt/data-sets/hg38/2bit/hg38.analysisSet.2bit"
#         - "seq\thg19\t/mnt/data-sets/hg19_GRCh37_random_chrM/seq"
#         - ...
galaxy_loc_file_data: null

# Galaxy installation location
galaxy_root: "{{ galaxy_dir }}/{{ galaxy_clone_dir }}"

# Is https enabled
enable_https: no

# Reference data for tool .loc files
# Define additional entries for .loc files as a
# dictionary with:
# - loc_file (name of the .loc file, relative to tool-data)
# - data     (data to add)
galaxy_loc_file_data:
