---
- name: "Install Python3 build dependencies for SL/CentOS"
  yum:
    name:
      - 'autoconf'
      - 'make'
      - 'automake'
      - 'gcc'
      - 'readline'
      - 'sqlite'
      - 'zlib'
      - 'bzip2-devel'
      - 'bzip2'
      - 'ncurses-devel'
      - 'ncurses'
      - 'openssl-devel'
      - 'openssl'
      - 'readline-devel'
      - 'sqlite-devel'
      - 'zlib-devel'
      - 'libffi-devel'
      - 'tkinter'
    state: 'present'
  when: python_user_id.stdout == "root"
