---
- name: "Install Python3 build dependencies for Ubuntu"
  apt:
    pkg:
      - 'build-essential'
      - 'gdb'
      - 'lcov'
      - 'pkg-config'
      - 'libbz2-dev'
      - 'libffi-dev'
      - 'libgdbm-dev'
      - 'libgdbm-compat-dev'
      - 'liblzma-dev'
      - 'libncurses5-dev'
      - 'libreadline6-dev'
      - 'libsqlite3-dev'
      - 'libssl-dev'
      - 'lzma'
      - 'lzma-dev'
      - 'tk-dev'
      - 'uuid-dev'
      - 'zlib1g-dev'
    state: 'present'
    update_cache: yes
  when: python_user_id == "root"
