# Install and configure postfix as null client for outgoing email
---
- name: "Install Postfix yum packages (RedHat)"
  yum:
    name: 'postfix'
    state: present
  when: ansible_distribution == "Scientific" or ansible_distribution == "CentOS"

- name: "Install Postfix apt packages (Ubuntu)"
  apt:
    pkg: 'postfix'
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Check if backup of Postfix configuration is present
  stat: path=/etc/postfix/main.cf.bak
  register: backup_postfix_default_conf

- name: Move default Postfix config file
  command: mv /etc/postfix/main.cf /etc/postfix/main.cf.bak
  when: backup_postfix_default_conf.stat.exists == False

- name: Check status of IPv6 support
  shell: 'test -f /proc/net/if_inet6 && echo yes || echo no'
  register: ipv6_supported

- name: Create null client Postfix config
  template:
    dest=/etc/postfix/main.cf
    src=postfix-main.cf.j2
  notify:
  - Reload Postfix

- name: Import generic maps file
  block:
    - name: Copy generic map file
      copy:
        src='{{ postfix_generic_maps }}'
        dest='/etc/postfix/generic'

    - name: Update generic maps
      command: postmap /etc/postfix/generic
  when: postfix_smtp_generic_maps|default(None) != None

- name: Start Postfix
  service:
    name=postfix
    enabled=on
    state=started
