---
# Supervisord defaults
supervisor_version: '4.2.2'
supervisor_install_dir: '/usr/local'

# Location of Python installation to use
supervisor_python_dir: '{{ supervisor_install_dir }}'
supervisor_python_exe: '{{ supervisor_python_dir }}/bin/python3'
