---
# Fetch the Let's Encrypt 'certbot' client
- name: Install certbot system dependencies
  yum:
    name:
      - gcc
      - dialog
      - augeas-libs
      - openssl
      - openssl-devel
      - libffi-devel
      - redhat-rpm-config
      - ca-certificates
      - python
      - python-devel
      - python-virtualenv
      - python-tools
      - python-pip
    state: present
  register: installed_certbot_dependencies

# Install certbot-auto for SSL certificate management
- name: "Install certbot-auto"
  get_url:
    url='https://dl.eff.org/certbot-auto'
    dest='/usr/local/bin/certbot-auto'
    mode=0755
