palfinder:
  hosts:
    130.88.97.220
  vars:
    # Server configuration
    galaxy_server_name: "palfinder.ls.manchester.ac.uk"
    enable_user_activation: yes
    # Galaxy base installation dir
    galaxy_install_dir: "/mnt/rvmi/palfinder/galaxy"
    # Secrets
    palfinder_secrets: palfinder_passwds.yml
    # Migrating to new VM
    ##galaxy_force_reinstall_python: yes
    ##galaxy_force_reinstall_venv: yes
    ##galaxy_reinstall_conda: yes
    ##galaxy_new_db_sql: "/mnt/rvmi/palfinder/galaxy/galaxy_palfinder.dump.2023-07-28.sql"
    # Job configuration
    galaxy_jse_drop_dir: "{{ galaxy_install_dir }}/palfinder/jse-drop-csf3"
    galaxy_jse_drop_galaxy_id: "{{ galaxy_name }}"
    enable_local_jse_drop: no
    galaxy_default_runner: "jse_drop_default"
    galaxy_job_destinations:
      - id: "jse_drop_default"
        runner: "jse_drop"
      - id: "jse_drop_8_cores"
        runner: "jse_drop"
        jse_drop_qsub_options: "-pe smp.pe 8"
        jse_drop_slots: "8"
    galaxy_tool_destinations:
      - id: "trimmomatic"
        destination: "jse_drop_8_cores"
    # Cluster needs to use its own virtual env
    galaxy_jse_drop_virtual_env: "/mnt/rvmi/palfinder/galaxy/shared/csf/galaxy/20.09/venv_py3.8"
    # Postfix/email configuration
    enable_smtp: yes
    # SSL configuration
    enable_https: yes
    # Demo data
    demo_data_dir: "{{ galaxy_install_dir }}/demo-data"
    galaxy_library_datasets:
      - file: "{{ demo_data_dir }}/miseq_R1.fq"
        type: "fastqsanger"
        library: "Example data/Fastqs"
      - file: "{{ demo_data_dir }}/miseq_R2.fq"
        type: "fastqsanger"
        library: "Example data/Fastqs"
