---
# Install EPEL repository
- name: Check if EPEL repo is enabled
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_status

- name: Install EPEL repo 
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
  when: epel_status.stat.exists == false
