# Install, configure and start Nginx on remote server

---
# Set up Nginx
- name: Install Nginx
  yum: name={{item}} state=present
  with_items:
  - nginx
  - libselinux-python
  - libsemanage-python
  - python-passlib
  register: nginx_installed

- name: Set sebooleans for httpd
  seboolean:
    name={{ item }} state=yes persistent=yes
  with_items:
  - httpd_can_network_connect
  - httpd_enable_homedirs
  when: nginx_installed | success
  register: httpd_set_sebooleans

- name: Start Nginx
  service:
    name=nginx
    state=started
    enabled=on
  when: httpd_set_sebooleans | success
