# Build and install ProFTP on the remote host
# We need v1.3.5+ for PBKDF2 support
# See http://galacticengineer.blogspot.co.uk/2015/02/ftp-upload-to-galaxy-using-proftpd-and.html
---
- name: Install ProFTPd build dependencies
  yum: state=present name={{item}}
  with_items:
  - postgresql-devel
  - openssl-devel
  - pam-devel
  register: installed_proftpd_dependencies

- name: Create build directory
  file:
    path='{{ build_dir }}'
    state=directory

- name: Download ProFTPd source
  get_url:
    url='https://github.com/proftpd/proftpd/archive/v{{ proftpd_version }}.tar.gz'
    dest='{{ build_dir }}'
  when: installed_proftpd_dependencies | success
  register: downloaded_proftpd_src

- name: Unpack ProFTPd source
  unarchive:
    src='{{ build_dir }}/proftpd-{{ proftpd_version }}.tar.gz'
    dest='{{ build_dir }}'
    copy=no
    owner=root
    group=root
    creates='{{ build_dir }}/proftpd-{{ proftpd_version }}'
  when: downloaded_proftpd_src | success
  register: unpacked_proftpd_src

- name: Install ProFTPd
  command:
    chdir='{{ build_dir }}/proftpd-{{ proftpd_version }}'
    {{item}}
    creates={{ proftpd_install_dir }}/sbin/proftpd
  with_items:
  - ./configure --prefix={{ proftpd_install_dir }} --disable-auth-file --disable-ncurses --disable-ident --disable-shadow --enable-openssl --with-modules=mod_sql:mod_sql_postgres:mod_sql_passwd
  - make
  - make install
  when: unpacked_proftpd_src | success
  register: installed_proftpd
