---
# Install and start the nfslock service
- name: Install NFS dependencies
  yum:
    name={{ item }} state=present
  with_items:
  - nfs-utils
  - rpcbind  
  register: installed_nfs_dependencies

- name: Start rpcbind and enable on boot
  service:
    name=rpcbind
    enabled=on
    state=started
  when: installed_nfs_dependencies is success
  register: started_rpcbind

- name: Start nfslock and enable on boot
  service:
    name=nfslock
    enabled=on
    state=started
  when:
  - started_rpcbind is success
  - ansible_distribution_major_version != "7"
  register: started_nfslock
