---
# Defaults for tool installation into Galaxy

# NB the following variables need to be set
# externally for this task:
#
# - galaxy_name
# - galaxy_root (or galaxy_dir)
# - galaxy_proxy_prefix
# - galaxy_user
# - master_api_key

# galaxy-utils should be installed under the 'bin' subdirectory
# of this location
galaxy_utils_dir: "/usr/local"

# Tools to be installed from the main toolshed
# If defined then should be a list e.g.
# galaxy_tools:
#      - tool: "column_maker"
#        owner: "devteam"
#        section: "Text Manipulation"
#      - tool: ...
#        owner: ...
#        section: ... etc
galaxy_tools: []

# Extra arguments to append to the 'install_tool.sh' script
# when installing from the tool shed
# - Set to "--check-install" to force post-install check on
#   tool existence after installing (increases installation
#   time but identifies tools where dependencies can't be
#   installed or new Galaxy version is needed)
# - Set to "--no-wait" to force tool installation not to wait
#   for installations to complete (fastest option if tools
#   are already installed, not recommended otherwise)
galaxy_install_tool_extra_args:

# Local tools to be installed
# If defined then should be a list e.g.
# local_galaxy_tools:
#      - name: "venn_diagram"
#        tool_files:
#          - "tools/venn_diagram/cistrome_venn_diagram.xml"
#          - "tools/venn_diagram/cistrome_venn_diagram.py"
#        section:
#          name: "ChIP-seq"
#          id: "ngs-chip-seq"
#      - name: ...
#        tool_files:
#          - ... etc
# NB the 'section' is optional; if omitted then the tool
# will appear in the top-level of the tool panel
local_galaxy_tools: []

# References to local tools which are managed outside
# the Ansible playbooks
# These will be added to the tool config XML
#
# If defined then should be a list of dictionaries, each
# of the form:
#
# - name: internal name for the tool (not used)
# - tool_xml_files: paths to XML files relative to the
#   'local_tools' directory (as a list)
# - section: dictionary with 'name' and 'id' of target section
#
# For example:
#
# local_galaxy_tool_references:
#      - name: "cas13_design"
#        tool_xml_files:
#          - "cas13_design/tools/cas13_design/RfxCas13d_GuideScoring.xml"
#          - "cas13_design/tools/cas13_design/guide_specificity_metrics.xml"
#          - "cas13_design/tools/cas13_design/pdf_report.xml"
#        section:
#          name: "Cas13 Guide Design"
#          id: "cas13-guide-design"
#      - name: ...
#        tool_files:
#          - ... etc
local_galaxy_tool_references: []

# Reference data for tool .loc files
#
# Specify as a list with additional entries for specific .loc
# files defined as dictionaries of the form:
#
# - loc_file (name of the .loc file, relative to tool-data)
# - data     (data to add, as a list)
#
# For example:
#
# galaxy_loc_file_data:
#     - loc_file: "alignseq.loc"
#       data:
#         - "seq\thg38\t/mnt/data-sets/hg38/2bit/hg38.analysisSet.2bit"
#         - "seq\thg19\t/mnt/data-sets/hg19_GRCh37_random_chrM/seq"
#         - ...
galaxy_loc_file_data: []

# Galaxy installation location
galaxy_root: "{{ galaxy_dir }}/{{ galaxy_clone_dir }}"

# Is https enabled
enable_https: no
