# Set up the Postgres Galaxy user and database
---
- name: Create PostgreSQL Galaxy user
  postgresql_user:
    name='{{ galaxy_user }}'
    password='{{ galaxy_user }}'
    role_attr_flags=NOSUPERUSER
    state=present
  when: installed_dependencies | success
  register: postgresql_galaxy_user_created

- name: Create PostgreSQL Galaxy database
  postgresql_db:
    name='{{ galaxy_db }}'
    owner='{{ galaxy_user }}'
    state=present
  when: postgresql_galaxy_user_created | success
  register: postgresql_galaxy_db_created
