---
- include: dependencies.yml

- include: database.yml
  become: yes
  become_user: postgres

- include: galaxy.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: reports.yml

- include: purgehistories.yml

- include: logrotate.yml

- include: nginxproxy.yml

- include: ftpupload.yml

- include: postfix.yml

- include: jsedrop.yml
  become: yes
  become_user: "{{ galaxy_user }}"
  when: enable_jsedrop

- include: uwsgi.yml
  become: yes
  become_user: "{{ galaxy_user }}"

- include: supervisor.yml
