---
- name: "Restart Nginx"
  service:
    name: "{{ nginx_service }}"
    state: reloaded

- name: "Restart Galaxy"
  shell:
    cmd: "{{ galaxy_utils_dir }}/bin/galaxyctl restart"
    chdir: "{{ galaxy_root }}"

- name: "Restart Galaxy reports"
  service:
    name: galaxy_reports
    state: restarted
