---
- name: "Restart Nginx"
  service:
    name: "{{ nginx_service }}"
    state: reloaded

- name: "Restart Galaxy"
  service:
    name: "galaxy"
    state: restarted

- name: "Restart Galaxy reports"
  service:
    name: galaxy_reports
    state: restarted
